[package]
name = "rusty_train"
version = "0.1.0"
authors = ["Rob Moss <robm.dev@gmail.com>"]
edition = "2018"

[dependencies]
# Include support for saving surfaces as PNG images.
cairo-rs = { version = "0.8", features = ["png", "pdf", "svg"] }
# Use the minimum supported version of GTK (3.16).
gtk = { version = "0.8", features = ["v3_16"] }
# Use the minimum supported version of GIO (2.44).
gio = { version = "0.8", features = ["v2_44"] }
gdk = "0.12"
glib = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"