[book]
authors = ["Rob Moss"]
language = "en"
multilingual = false
src = "src"
title = "Navigating 18xx: calculating optimal routes"

[rust]
edition = "2018"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = true
copy-fonts = false

[output.linkcheck]
optional = true
